-- RECIPES 테이블 생성
CREATE TABLE RECIPES (
    RECIPE_ID NUMBER PRIMARY KEY,
    RECIPE_NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    INSTRUCTIONS CLOB
);

-- INGREDIENTS 테이블 생성
CREATE TABLE INGREDIENTS (
    INGREDIENT_ID NUMBER PRIMARY KEY,
    RECIPE_ID NUMBER,
    INGREDIENT_NAME VARCHAR2(100) NOT NULL,
    QUANTITY VARCHAR2(50),
    CONSTRAINT FK_RECIPES FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES (RECIPE_ID) ON DELETE CASCADE
);

-- RECIPES 테이블용 시퀀스 생성
CREATE SEQUENCE RECIPES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
/

-- INGREDIENTS 테이블용 시퀀스 생성
CREATE SEQUENCE INGREDIENTS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
/

-- RECIPES 테이블에 INSERT 시 ID 자동 할당 트리거
CREATE OR REPLACE TRIGGER RECIPES_TRG
BEFORE INSERT ON RECIPES
FOR EACH ROW
BEGIN
  :NEW.RECIPE_ID := RECIPES_SEQ.NEXTVAL;
END;
/

-- INGREDIENTS 테이블에 INSERT 시 ID 자동 할당 트리거
CREATE OR REPLACE TRIGGER INGREDIENTS_TRG
BEFORE INSERT ON INGREDIENTS
FOR EACH ROW
BEGIN
  :NEW.INGREDIENT_ID := INGREDIENTS_SEQ.NEXTVAL;
END;
/
